"""Concept 17: animated puppet stage with Ollama-generated replies.

Run:
    ollama serve
    ollama pull llama3.2
    uv run python src/animated_puppet_ollama.py

This extends the animated puppet stage so actor spoken lines come from local
Ollama (`llama3.2` by default). If Ollama is unavailable, the app falls back to
the deterministic line generator from the previous exercise.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from pathlib import Path
from typing import Any

import gradio as gr
from ollama import Client as OllamaClient

BASE_PATH = Path(__file__).with_name("animated_puppet_stage.py")
SPEC = importlib.util.spec_from_file_location("animated_stage", BASE_PATH)
if SPEC is None or SPEC.loader is None:
    raise RuntimeError("Could not load src/animated_puppet_stage.py")
animated_stage = importlib.util.module_from_spec(SPEC)
sys.modules["animated_stage"] = animated_stage
SPEC.loader.exec_module(animated_stage)


DEFAULT_MODEL = os.environ.get("OLLAMA_MODEL", "llama3.2")


def _format_transcript(session: dict[str, Any]) -> str:
    rows = []
    for item in session.get("transcript", [])[-8:]:
        who = item.get("who", "Actor")
        text = str(item.get("text", "")).strip()
        if text:
            rows.append(f"{who}: {text}")
    return "\n".join(rows) or "(curtain just rose)"


def _format_roster(session: dict[str, Any]) -> str:
    rows = []
    for actor in session["actors"]:
        rows.append(
            f"- {actor['name']}: goal={actor['goal']}; secret={actor['secret']}; "
            f"style={actor['style']}; tools={', '.join(actor.get('tools', [])) or 'none'}"
        )
    return "\n".join(rows)


def _ollama_reachable(model: str) -> bool:
    try:
        OllamaClient().show(model)
        return True
    except Exception:
        return False


def ollama_speaker_line(
    session: dict[str, Any],
    speaker: dict[str, Any],
    model: str,
) -> str | None:
    rules = "; ".join(session.get("reality_rules", [])[-3:]) or "normal stage rules"
    tools = "\n".join(session.get("tool_log", [])[-4:]) or "(no tools used yet)"
    system = (
        "You are writing ONE short spoken line for a puppet theater actor. "
        "Return dialogue only. No name label, no stage direction, no markdown. "
        "Stay in character and keep it under 35 words."
    )
    user = f"""
Setting: The Runaway Puppet Show.
Current actor: {speaker['name']}
Actor goal: {speaker['goal']}
Actor secret, private: {speaker['secret']}
Actor style: {speaker['style']}

Reality rules: {rules}
Recent transcript:
{_format_transcript(session)}

Recent tool results:
{tools}

Full roster:
{_format_roster(session)}

Write {speaker['name']}'s next spoken line.
"""
    try:
        response = OllamaClient().chat(
            model=model,
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": user},
            ],
            options={"temperature": 0.85, "num_predict": 90},
            stream=False,
        )
    except Exception as exc:
        session.setdefault("director_log", []).append(
            f"[LLM] Ollama unavailable for {model}: {type(exc).__name__}. Using fallback."
        )
        return None

    text = (response.message.content or "").strip().strip('"')
    text = " ".join(text.split())
    if not text:
        return None
    return text[:320]


def make_speaker_line(use_ollama: bool, model: str):
    fallback = animated_stage.agentic_tts.agentic_base.speaker_line

    def speaker_line(session: dict[str, Any], speaker: dict[str, Any]) -> str:
        if not use_ollama:
            return fallback(session, speaker)
        generated = ollama_speaker_line(session, speaker, model)
        if generated is None:
            return fallback(session, speaker)
        animated_stage.agentic_tts.agentic_base.append_director(
            session, f"[LLM] {speaker['name']} line generated by Ollama model `{model}`."
        )
        return generated

    return speaker_line


def run_one_beat_ollama(
    session: dict[str, Any],
    use_ollama: bool,
    model: str,
):
    model = (model or DEFAULT_MODEL).strip() or DEFAULT_MODEL
    base = animated_stage.agentic_tts.agentic_base
    original = base.speaker_line
    base.speaker_line = make_speaker_line(bool(use_ollama), model)
    try:
        yield from animated_stage.agentic_tts.run_one_beat_with_tts(session)
    finally:
        base.speaker_line = original


def build_app() -> gr.Blocks:
    with gr.Blocks(title="Hackathon Ollama Puppet Stage - Ollama Puppet Stage") as demo:
        initial = animated_stage.agentic_tts.agentic_base.initial_session()
        state = gr.State(initial)
        gr.Markdown(
            "## The Runaway Puppet Show — Ollama Version\n"
            "Animated agentic puppets with TTS. Actor lines are generated with local "
            "`llama3.2` through Ollama when enabled. Decisions/tools remain deterministic "
            "so the demo stays reliable."
        )
        stage = gr.HTML(animated_stage.render_theater_stage(initial))
        with gr.Row():
            use_ollama = gr.Checkbox(value=True, label="Use Ollama for actor lines")
            model = gr.Textbox(label="Ollama model", value=DEFAULT_MODEL)
            run = gr.Button("Run one beat", variant="primary")
            audit = gr.Button("Request audit")
        with gr.Row():
            prop = gr.Textbox(label="Throw prop", value="rubber duck", scale=2)
            prop_btn = gr.Button("Throw")
            summon_name = gr.Textbox(label="Summon actor", value="Oracle Spoon")
            summon = gr.Button("Summon")
            reset = gr.Button("Reset")
        audio = gr.Audio(
            label="Puppet voice",
            type="filepath",
            autoplay=True,
            interactive=False,
        )
        with gr.Accordion("Transcript", open=True):
            chat = gr.Chatbot(label="Stage transcript", height=260)
        with gr.Accordion("Behind the curtain", open=False):
            with gr.Row():
                director = gr.Code(label="Director / policy log", language=None, lines=16)
                tools = gr.Code(label="Tool log", language=None, lines=16)

        outputs = [state, stage, chat, director, tools, audio]
        demo.queue(default_concurrency_limit=20)
        run.click(run_one_beat_ollama, inputs=[state, use_ollama, model], outputs=outputs)
        audit.click(animated_stage.agentic_tts.queue_audit, inputs=[state], outputs=outputs)
        prop_btn.click(
            animated_stage.queue_prop_with_animation,
            inputs=[state, prop],
            outputs=outputs,
        )
        summon.click(
            animated_stage.summon_actor_immediately,
            inputs=[state, summon_name],
            outputs=outputs,
        )
        reset.click(animated_stage.reset_session, outputs=outputs)

    return demo


def main() -> None:
    build_app().launch(
        server_name="0.0.0.0" if os.environ.get("SPACE_ID") else "127.0.0.1",
        server_port=int(os.environ.get("PORT", "7864")),
        show_error=True,
        css=animated_stage.CSS,
    )


if __name__ == "__main__":
    main()
